### ISSUE TITLE
GDI resources are not released after capture

### ISSUE THREAD

**Issue by MikeWinter** [56kyle/window_input#2]
The `capture` method acquires resources from the GDI API. However, these resources are never released to the OS eventually leading to errors. The method should clean up once the image has been obtained.

### Reproduction steps

1. Open Notepad
2. Run the [test script](https://gist.github.com/MikeWinter/2fa3cfb0c5a4a93081ca5d3937136750). This assumes the default window title of "Untitled - Notepad"

### Expected results

- The script exits normally

### Actual results

- The script terminates with an assertion error; resources have leaked from the `capture` method

### Suggested fix

I have [a proposed fix](https://github.com/56kyle/window_input/compare/master...MikeWinter:release-gdi-resources) that wraps the sequence of calls with a try/finally statement. I can raise this as a pull request if that's helpful.

**Comment by 56kyle** [comment]
closing due to merging of mentioned fix, thanks again and sorry for the delay
