### ISSUE TITLE
Device context handle of existing window is deleted after retrieving pixel

### ISSUE THREAD

**Issue by MikeWinter** [56kyle/window_input#3]
The `pixel` method attempts to release the device context it acquired, but it does so using `DeleteDC`. This function should only be used with contexts that have been created by the user via `CreateDC` and the like. [Handles obtained by `GetDC` or `GetWindowDC` must use `ReleaseDC`](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-deletedc#remarks).

There's the additional problem that this attempt to relinquish the device context isn't always called which can leak resources, similar to #2.

I propose [a fix](https://github.com/56kyle/window_input/compare/master...MikeWinter:release-device-context) to use the correct function and ensure it's always called before returning.

**Comment by 56kyle** [comment]
merged said fix, ty for the help and sorry for the delay
