### ISSUE TITLE
Is this library Linux-compatible?

### ISSUE THREAD

**Issue by ItsLiyua** [56kyle/window_input#5]
I saw, that this library uses modules like win32gui. Does that mean it is only for windows and does not work for Linux or am I overthinking this?

**Comment by 56kyle** [comment]
sorry for the incredibly late reply, I just never saw an alert for this and was going through my email. It's Windows only unfortunately

**Comment by ItsLiyua** [comment]
Thanks for still replying! I dropped the project but it would not have worked anyways so the late reply is not a problem! But still thabk you for replying even if it was late.
